# Change these first
owner: paywatchglobal # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Production Business-Logic services
    url: https://20.24.157.72/agghealth/health
    __dangerous__insecure: true
    maxResponseTime: 30000
    __dangerous__body_down_if_text_missing: '"BizLogicAdmin":"healthy","BizLogicWork":"healthy","BizLogicUser":"healthy","BizLogicReport":"healthy","BizLogicGeneral":"healthy","BizLogicFinance":"healthy","BizLogicIntegration":"healthy"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Paywatch Uptime Monitoring
  introTitle: "**Paywatch Uptime Monitoring**"
  introMessage: Paywatch Uptime Monitoring via Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
